export enum ModifierEffect {
  Double = '2x',
  NoAttack = 'No damage',
  Poison = 'Poison',
  Wound = 'Wound',
  Immobilize = 'Immobilize',
  Disarm = 'Disarm',
  Stun = 'Stun',
  Muddle = 'Muddle',
  Invisible = 'Invisible',
  Strengthen = 'Strengthen',
  Fire = 'Fire',
  Air = 'Air',
  Ice = 'Ice',
  Earth = 'Earth',
  Light = 'Light',
  Dark = 'Dark',
  Curse = 'Curse',
  Bless = 'Bless',
}
